version: 0.2.11

user:
  name: 白云苍狗
  avatar: /images/avatar.jpg
  title: 一觉游仙好梦，任它竹冷松寒。轩辕事，古今谈，风流河山。沉醉负白首，舒怀成大观。醒，亦在人间；梦，亦在人间
  desc: 醒，亦在人间；梦，亦在人间

cloudbase:
  enable: true
  env: h-17b316

favicon:
  visibilitychange: true
  narmal: /images/favicon.png
  hidden: /images/failure.png
  show_text: (/≧▽≦/)咦！又好了！
  hide_text: (●—●)喔哟，崩溃啦！
  apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo.svg

post_wordcount:
  wordcount: true # 单篇 字数统计
  min2read: true # 单篇 阅读时长

#开启
sw: true

#
canonical: true

cdn:
  css: 
    - //at.alicdn.com/t/font_1518765_5jbj7btfht2.css
    - //cdn.jsdelivr.net/gh/MoePlayer/APlayer@1.10.1/dist/APlayer.min.css
  js:
    - //cdn.jsdelivr.net/npm/nprogress@0.2.0/nprogress.min.js
    - //cdn.jsdelivr.net/gh/MoePlayer/APlayer@1.10.1/dist/APlayer.min.js
    - //cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js
    - //cdn.jsdelivr.net/npm/jquery-pjax@2.0.1/jquery.pjax.min.js
    - //at.alicdn.com/t/font_1518765_5jbj7btfht2.js
    - //imgcache.qq.com/qcloud/tcbjs/1.6.0/tcb.js
    - //cdn.jsdelivr.net/npm/medium-zoom@1.0.6/dist/medium-zoom.min.js

menu:
  nav:
    - title: 白云苍狗
      url: /
    - title: 归档
      url: /archives
      icon: shijian
    - title: 友情链接
      url: /links
      icon: links
  aside:
    - title: 首页
      url: /
      icon: home
    - title: 友情链接
      url: /links
      icon: links
    - title: 留言
      url: /comment
      icon: comment
    - title: RSS
      url: /atom.xml
      icon: rss
    - title: Github
      url: //github.com/MaLuns
      icon: github
    - title: Gitee
      url: //gitee.com/ml13
      icon: gitee 
    - title: 联系我
      url: tencent://message/?uin=384399021&amp;Site=有事Q我&amp;Menu=yes
      icon: qq
   # - title: FlexView
   #   url: https://www.imalun.com/flex.html
   #   icon: flex 

rss: atom.xml

# 友链
links:
  - name: hexo
    url: //hexo.io/
    image: //d33wubrfki0l68.cloudfront.net/6657ba50e702d84afb32fe846bed54fba1a77add/827ae/logo.svg
    desc: 快速、简洁且高效的博客框架
  - name: 随心
    url: //uiluil.com/
    image: //uiluil.com/medias/logo.png
    desc: 从来没有真正的绝境, 只有心灵的迷途
  - name: 白云苍狗
    url: //www.imalun.com/
    image: //www.imalun.com/images/avatar.jpg
    desc: 醒，亦在人间；梦，亦在人间E
  - name: 阿龙爱吃肉
    url: //3zi.cn
    image: //i.loli.net/2021/03/28/IZilAJ293tVpwLK.jpg
    desc: 学习过程中和工作中的新知识点，范围：Java，MySQL，Layui…
  - name: 盒子萌
    url: //www.boxmoe.com
    image: //www.boxmoe.com/file/100logo.png 
    desc: 一个基于内容分享,创作与灵感结合的折腾笔记博客
